server:
  port: 80
spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false
  zipkin:
    baseUrl: http://zipkin.svc.cluster.local:9411/api/v2/spans
eureka:
  instance:
    hostname: discovery.svc.cluster.local
  server:
    peer-node-read-timeout-ms: 50000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  zipkin:
    tracing:
      endpoint: ${spring.zipkin.baseUrl}