server:
  port: ${services.inventory.port}
spring:
  application:
    name: inventory-service
    label: ${spring.application.name}
    base-package: ${services.inventory.packages}
upload:
  path: /test
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.client.serviceUrl.defaultZone}
management:
  zipkin:
    tracing:
      endpoint: ${spring.zipkin.baseUrl}